export interface Issue {
  id: string;
  title: string;
  description: string;
  category: 'pothole' | 'water_leakage' | 'streetlight' | 'waste_management' | 'infrastructure' | 'other';
  status: 'reported' | 'investigating' | 'in_progress' | 'resolved';
  urgency: 'low' | 'medium' | 'high' | 'critical';
  latitude: number;
  longitude: number;
  sector: string; // e.g. "Sector 4 (Northside)", "Sector 2 (Civic Center)"
  upvotes: number;
  upvotedByUserIds: string[];
  imageUrl?: string;
  videoUrl?: string;
  reportedBy: {
    name: string;
    email: string;
    points: number;
  };
  createdAt: string;
  ticketId?: string;
  verificationScore: number; // calculated from upvotes and additional reviews
  verificationStatus: 'unverified' | 'validating' | 'verified';
  timeline: {
    status: string;
    title: string;
    description: string;
    timestamp: string;
    updatedBy?: string;
  }[];
}

export interface Ticket {
  id: string;
  issueId: string;
  department: string; // e.g., "Department of Public Works", "Water Sanitation Board"
  assignedCrew?: string;
  priorityScore: number; // (urgency factor * 15) + (upvotes * 2)
  targetResolutionDate: string;
  dispatchMemo?: string; // official memo text generated by AI
  officialNotes?: string;
  responseLog: {
    timestamp: string;
    message: string;
    sender: 'authority' | 'system' | 'citizen';
  }[];
}

export interface LeaderboardEntry {
  rank: number;
  name: string;
  points: number;
  reportsSubmitted: number;
  verificationsCompleted: number;
  badge: string;
  badgeColor: string;
}

export interface PredictiveInsight {
  id: string;
  title: string;
  sector: string;
  category: string;
  riskProbability: number; // percentage (e.g. 84)
  triggerFactors: string[];
  recommendedAction: string;
  severity: 'low' | 'medium' | 'high';
}
